esphome:
  name: luces_cocina
  platform: ESP8266
  board: esp01_1m

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: !secret ip_luz_cocina
    gateway: !secret gateway
    subnet: !secret subnet

  # # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

text_sensor:
  - platform: version
    name: Luces Cocina Version
  - platform: wifi_info
    ip_address:
      name: "IP Luces Cocina"

sensor:
  - platform: uptime
    name: "Luces Cocina Uptime"
    update_interval: 60s

button:
  - platform: restart
    name: "Luces Cocina Restart"

switch:
  - platform: gpio
    name: Luz Labores
    pin: GPIO5
    id: relay_1
  - platform: gpio
    name: Luz Cocina
    pin: GPIO12
    id: relay_2

binary_sensor:
  - platform: status
    name: "Luces Cocina"

  - platform: gpio
    name: Luz Cocina
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay_2
  - platform: gpio
    name: Luz Labores
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay_1

status_led:
  pin:
    number: GPIO13
    inverted: True
